language: java
jdk: openjdk11
env:
  global:
    - GITHUB_ACTOR=araqnid
    - secure: "2u2sXH4ajzm2wXKvyTMeEfgDgUmZU48aFK/oPPG0S3ttCvKvJaBNbsAv5/Nu6WdymaP0ZGmfd6F3j9XvAVzBFBz9Ihh/utFzwxnOJEseyjr2BBZvoFvn6V5IQ1BziXm7TzEwEOEE4uTwMMdej/ZJe2ogKL1awpfYJsNI2ACslkPTTtoz2FD7z5jIthVNFvHlqI52qCRCB9sAM7lSfJPU++M8m9krlZmrvgQ6i3PUX7f1yY71P+29atEugJO0deJZLzpup13UN2VTRw4OFGWQk1Rbd//aiZjagwD8zsvaIcgWBpTk2QrocNy03RGzYtfnh0dg3CPyucAlEzmfRqQYUe/IFZRhTvF/gII7rPZUdQlC9uSvHfrIDHwqtKWq+PQ2vlH6HE0Q2yLdJ8n7lctw2mXIikfF9zo+BkwjseorVRZKJ3AH3tJ3r9l8Np3xAdk7ofmCkZblp9ZsGAmskyB2gEqqWNIBUzL6HvnnxOEbeHgennA8JvhNrpWqiL14oIcvy0ufMB9L4DZtPdoMSCbUK80L112pVfjCXsVczFqFOhJVuY1SzyJqp8gKV7ekktDZUKA6mLISgFBrSy6ngMr3ZONIatRjldvcDM5+r1WljieTBFw/Kkci/03Wb3hS1AWJJ8gNuFH88olbslpSu7jP9VqvITt1gNtFhdSMsr9ZUI8="
